/**
 * EdoriResult
 *
 * Authoritative output of the EDORI
 * calculation engine.
 */

import type { Driver }
from "./Driver";


import type { OperationalState }
from "../config/operationalStates";


export interface EdoriResult {

    /**
     * Overall EDORI score from 0–100.
     */
    score:number;


    /**
     * Human-readable operational status.
     */
    status:string;


    /**
     * Full operational-state configuration.
     */
    operationalState:OperationalState;


    /**
     * Individual scoring domains.
     */
    demandScore:number;

    boardingScore:number;

    hospitalScore:number;

    acuityScore:number;

    forecastScore:number;


    /**
     * Factors contributing to the score.
     */
    drivers:Driver[];


    /**
     * Basic recommendations generated by
     * the calculation engine.
     */
    recommendations:string[];


    /**
     * Time the calculation was completed.
     */
    timestamp:Date;

}